### ISSUE TITLE
Better pattern

### ISSUE THREAD

**Issue by PepeLopez** [kurobeats/Fail2ban-GROK-Log-Pattern#1]
Hi,

I used your pattern as starting point. Because fail2ban in v0.10+ can handle IPv6 you might change the pattern. Furthermore on "service" (the name of the triggered fail2ban jail) might contain "-" or other chars, the grok pattern "WORD" might not work then.

OLD version:
`    "pattern" : "%{TIMESTAMP_ISO8601:timestamp},%{INT:fail2ban_digit} fail2ban.%{WORD:fail2ban_action} *\[%{INT:fail2ban_digit2}\]: %{LOGLEVEL:level} *\[%{WORD:service}\] %{WORD:ban_status} %{IPV4:clientip}"
`

NEW version:
`    "pattern" : "%{TIMESTAMP_ISO8601:timestamp},%{INT:fail2ban_digit} fail2ban.%{WORD:fail2ban_action} *\[%{INT:fail2ban_digit2}\]: %{LOGLEVEL:level} *\[%{GREEDYDATA:service}\] %{WORD:ban_status} %{IP:clientip}"
`

You want it even better? In logstash I'm namespacing the output, to have a cleaner access (e.g. in Kibana Discover tab), here's my very own, namespaced pattern:
`%{TIMESTAMP_ISO8601:[f2b][timestamp]},%{INT:[f2b][fail2ban_digit]} fail2ban.%{WORD:[f2b][fail2ban_action]} *\[%{INT:[f2b][fail2ban_digit2]}\]: %{LOGLEVEL:[f2b][loglevel]} *\[%{GREEDYDATA:[f2b][service]}\] %{WORD:[f2b][ban_status]} %{IP:[f2b][clientip]}`

The output will then be:

> {
>   "[f2b][timestamp]": "2018-01-01 12:00:00",
>   "[f2b][service]": "my-own-jail",
>   "[f2b][clientip]": "1.2.3.4",
>   "[f2b][fail2ban_action]": "actions",
>   "[f2b][ban_status]": "Ban",
>   "[f2b][fail2ban_digit]": "123",
>   "[f2b][fail2ban_digit2]": "4567",
>   "[f2b][loglevel]": "NOTICE"
> }

**Comment by kurobeats** [comment]
I'll replace with your improved version, thanks for the contribution!
