### ISSUE TITLE
Regarding your "To Do/Help Wanted"

### ISSUE THREAD

**Issue by megan201296** [kurobeats/Fail2ban-GROK-Log-Pattern#2]
The first "random" number (`,INT`) is actually part of the timestamp. It is `ISO8601` timestamp format's representation of the fraction of the second. So it is not a separate field.

**Comment by kurobeats** [comment]
thank you! Is this still an issue after the latest pull?

**Comment by megan201296** [comment]
@kurobeats unfortunately I no longer work in the environment I was using this in before so am unable to test. I ended up editing it manually in that environment anyway, just added this to give you a heads up. Thanks for fixing.
